### ISSUE TITLE
Can the repo support roi feature extraction

### ISSUE THREAD

**Issue by starsholic** [tridivb/slowfast_feature_extractor#12]
**Describe the bug**

**To Reproduce**
Steps you followed while encountering the bug

**Expected behavior**

Thanks for your work! The repo now support extract video feature from a video or a set of frames
It will be better if it supports the ROI feature extraction part.

**Screenshots/Code Output**
If applicable, add screenshots or code output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 16.04]
 - Python Version
 - PyTorch version

**Additional context**

**Comment by tridivb** [comment]
Hello,

Thank you for using the framework and the suggestion. Could you elaborate on that? As far as I know, the Slowfast model does not make use of separate ROIs.

**Comment by starsholic** [comment]
Hi,
 
When training on the AVA dataset, the SlowFast model using ROI feature to classify actions. The related code is in the slowfast/model/head_helper.py   ResNetRoiHead class    


```
def forward(self, inputs, bboxes):
        assert (
            len(inputs) == self.num_pathways
        ), "Input tensor does not contain {} pathway".format(self.num_pathways)
        pool_out = []
        for pathway in range(self.num_pathways):
            t_pool = getattr(self, "s{}_tpool".format(pathway))
            out = t_pool(inputs[pathway])
            assert out.shape[2] == 1
            out = torch.squeeze(out, 2)

            roi_align = getattr(self, "s{}_roi".format(pathway))
            out = roi_align(out, bboxes)

            s_pool = getattr(self, "s{}_spool".format(pathway))
            pool_out.append(s_pool(out))

        # B C H W.
        x = torch.cat(pool_out, 1)

        # Perform dropout.
        if hasattr(self, "dropout"):
            x = self.dropout(x)

        x = x.view(x.shape[0], -1)
        x = self.projection(x)
        x = self.act(x)
        return x
```


Here  out = roi_align(out, bboxes) is the ROI feature in a set of frames, right?

It will be great if the toolbox support object detect and feature extractract, such as person detect and person feature extract in a video or a set of frames.

**Comment by tridivb** [comment]
Unfortunately, I do not have the bandwidth to work on this at the moment. So closing this issue for now.
