### ISSUE TITLE
Can I extract video feature based on 1FPS video frames?

### ISSUE THREAD

**Issue by starsholic** [tridivb/slowfast_feature_extractor#13]
**Describe the bug**

**To Reproduce**
Steps you followed while encountering the bug

**Expected behavior**
For some reasons, I can't get raw video for feature extraction, only get 1FPS frames of the video. Could I extract the video feature based on these 1FPS frames?

**Screenshots/Code Output**
If applicable, add screenshots or code output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 16.04]
 - Python Version
 - PyTorch version

**Additional context**

**Comment by tridivb** [comment]
Hi, Thank you for the question. Do you mean sampling 1 frame every second for processing? Yes, just set the OUT_FPS config parameter to 1.
