### ISSUE TITLE
请教一下配置（有关采样率）

### ISSUE THREAD

**Issue by splinter21** [tridivb/slowfast_feature_extractor#14]
我下载了一个8x8的slowfast，我的理解是每8帧选一个中间帧，中间帧邻近共计8帧跑一次视频特征提取，所以出来的shape[0]预期应该是总帧数//8
我跑了一个5000帧25fps的视频，设置IN_FPS=OUT_FPS=25，NUM_FRAMES=SAMPLING_RATE=8，最后的特征维度是(5000,2304)，shape[0]不是5000//8，这意味着他并没有每隔8帧取一次的这个sample rate？
谢谢！

**Comment by splinter21** [comment]
看了videoset.py代码我理解了

SAMPLING_RATE采样参数没有用到，而in_fps/out_fps的意思是抽帧

比如30in，10out，意味着每3秒抽1帧

而滑动窗口固定为1了，没有用到SAMPLING_RATE

也即，
（1）先根据in-out-fps进行抽帧采样
（2）从第一帧到最后1帧，每隔1帧滑动一次，选取邻近NUM_FRAMES个
这2个我打算改进下
（3）滑动窗口不能自定义
（4）用到的重复帧/特征没有复用而是重复计算了

**Comment by tridivb** [comment]
Hello, 

Unfortunately, I do not understand what you wrote. Could you please translate your questions to english?
