### ISSUE TITLE
Does it support distributed inference?

### ISSUE THREAD

**Issue by starsholic** [tridivb/slowfast_feature_extractor#16]
**Describe the bug**
When I use 6gpus to inference the video,I find that the speed is not faster than 1gpu, does it support distributed inference?

**To Reproduce**
Steps you followed while encountering the bug

**Expected behavior**

**Screenshots/Code Output**
If applicable, add screenshots or code output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 16.04]
 - Python Version
 - PyTorch version

**Additional context**

**Comment by tridivb** [comment]
Thank you for the question. No distributed inference is not supported as to process videos, they have to be decoded first. Therefore it is processed frame by frame. Another approach would be to pre-extract the frames and then run inference on them. That would allow processing them in batches.
