### ISSUE TITLE
About the window of extractor and numbers of features

### ISSUE THREAD

**Issue by foolishhmy** [tridivb/slowfast_feature_extractor#7]
Thanks for your great work! I read you code but I am not sure if I understand right. For every frame in the video, the extract will generate a 1-D feature vector, and the length of window equals the step_size * out_size, step_size is the drop ratio of the window. I have a question about what does the 8x8 mean in the pre-trained model, previously I think for every 8*8 frames we should output a feature, but now it seems to mean the size of the window? Looking forward to your reply!

**Comment by tridivb** [comment]
Hello,

Thank you for using the codebase. Do you mean the 8x8 in the name of the pre-trained model? That is a reference to how the input was sampled for that particular model. In this case, it means 8 frames sparsely sampled from a raw clip of size 64 frames, with a temporal stride of 8. I would suggest reading the paper (https://arxiv.org/pdf/1812.03982.pdf - Section 3.4)  for a more detailed explanation.

**Comment by tridivb** [comment]
@foolishhmy I might have misunderstood your original question. Could you confirm if the above answer is what you were looking for? Please note, for the feature extraction purposes, the window size has been customized by adding the video fps and out fps parameters. They are not part of the original slowfast codebase.

**Comment by tridivb** [comment]
Closing the issue in the absence of followup.
