### ISSUE TITLE
Rgb features only?

### ISSUE THREAD

**Issue by ZhengLeon** [tridivb/slowfast_feature_extractor#9]
Hi,
Thanks for your great job!
I wonder if the flow features can be extracted  from videos by you code?

**Comment by tridivb** [comment]
Hello,

Thank you for using the framework. Unfortunately no, in its current state it does not support Flow features. You can of course try by tuning the model parameters like input number of channels and dataset code. But you would have to train your own model.

**Comment by ZhengLeon** [comment]
@tridivb 
Thanks for your reply!
But I got another problem now, the code seems working but no output comes, displaying:

**Loading Video List ...
Done
----------------------------------------------------------
1 videos to be processed...
----------------------------------------------------------
0. Processing /home/work/slowfast_feature_extractor/video/0a244c71991f386b161bcd787c7da607...**
So, does it really work?

**Comment by tridivb** [comment]
Hi, 

Thanks for bringing this to my attention. Please follow the new issue #10. I am closing this as the original question has been addressed. To report bugs, please follow the bug report template next time.
